### ISSUE TITLE
Support for EncryptedSharedPreferences

### ISSUE THREAD

**Issue by rafid059** [AutSoft/Krate#10]
It would be nice if Krate supported [EncryptedSharedPreferences](https://developer.android.com/reference/kotlin/androidx/security/crypto/EncryptedSharedPreferences) in a separate artifact. Any plans for this?

**Comment by zsmb13** [comment]
You can provide your own `SharedPreferences` instance for Krate to use, as the `Krate` only defines a property of that type, everything else works off of that. If you pass in an `EncryptedSharedPreferences` instance, it should work.

The demo app has an example of custom `SharedPreferences` being set in a `Krate`: https://github.com/AutSoft/Krate/blob/master/app/src/main/java/hu/autsoft/krateexample/krates/ExampleCustomKrate.kt#L19-L21
