### ISSUE TITLE
Add support for Encryption

### ISSUE THREAD

**Issue by tzutolin** [AutSoft/Krate#11]
Is it possible to support sharepreference encryption with AndroidX Security Library?

https://www.bignerdranch.com/blog/encrypting-shared-preferences-with-the-androidx-security-library/

**Comment by zsmb13** [comment]
Please see https://github.com/AutSoft/Krate/issues/10

**Comment by tzutolin** [comment]
> Please see #10

Thanks, I didn't notice this has been mentioned by someone.
