### ISSUE TITLE
Add support for Serializable object

### ISSUE THREAD

**Issue by fonix232** [AutSoft/Krate#2]
It would be really nice if serialization was supported, on at least objects that extend the `Serializable` interface.

Values would be stored as string, and accessing/writing them would trigger a simple gson/moshi/etc. (de)serialization.

**Comment by antercepter** [comment]
Can I help you with this?

**Comment by fonix232** [comment]
@antercepter do you have an already working solution that works with Krate?

**Comment by antercepter** [comment]
@fonix232 I didn't  use Krate on my projects, but I have extensive experience in Android development, here's [my linkedin](https://www.linkedin.com/in/serghei-ceacal-1149467b/)

**Comment by zsmb13** [comment]
I'll look into this eventually, but I can't make any promises for the timeline right now.

**Comment by zsmb13** [comment]
This is covered by the Gson and Moshi artifacts.
