### ISSUE TITLE
Artifact on maven central is missing aar

### ISSUE THREAD

**Issue by Tapchicoma** [AutSoft/Krate#5]
If you open https://repo1.maven.org/maven2/hu/autsoft/krate/0.1.1/ link, you will see that `0.1.1` version files are missing actual `aar` file.

This brings problems if `mavenCentral()` is used to get artifacts before `jcenter()`.

**Comment by zsmb13** [comment]
Indeed, this is a result of a failed attempt at setting up MavenCentral publication - until now, the library was only available from JCenter. Unfortunately I ran into a weird bug with uploads to MavenCentral, and I need to sort out some configuration issues there. I'm trying to fix it ASAP, hopefully within days.

Unfortunately there's no way for me to remove this bad release from MavenCentral, instead I will have to create a successful release with a new version number of MavenCentral to clear it up.

Sorry for the inconvenience.

**Comment by zsmb13** [comment]
Republished under the version number `0.1.2` on MavenCentral. @Tapchicoma, can you please confirm that it's working correctly now?

**Comment by Tapchicoma** [comment]
works now :+1:
