### ISSUE TITLE
How to add dynamic sp names  

### ISSUE THREAD

**Issue by wangyuanfei** [AutSoft/Krate#9]
How to add dynamic sp names? thanks

**Comment by zsmb13** [comment]
If you're using `SimpleKrate`, you can pass in the name of the `SharedPreferences` you want to use as a second constructor parameter: https://github.com/AutSoft/Krate/blob/master/krate/src/main/kotlin/hu/autsoft/krate/SimpleKrate.kt#L10

Does that answer your question?

**Comment by wangyuanfei** [comment]
Sorry my question was not clear
for example
 var isLogin by booleanPref("IS_LOGIN_${id}", false)
Dynamic key (${id})

**Comment by zsmb13** [comment]
It's not possible to change the key of a preference declared with `Krate` completely dynamically, due to the property access it provides through delegates - there's simply nowhere to place a dynamic key within this syntax:

```kotlin
myKrate.someProperty = "value"
```

So the best you can do is parameterize the entire Krate, like so:

```kotlin
class UserPreferences(context: Context, userId: String) : SimpleKrate(context) {
    var isLoggedIn: Boolean by booleanPref("IS_LOGGED_IN_$userId")
}
```

**Comment by wangyuanfei** [comment]
yahaha!!，  very good
